djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

djangonautic/articles/urls.py
from django.conf.urls import url
from . import views

app_name = "articles"

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

djangonautic/djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        #return self.body[:100] + '...'
        return self.body[:100] + '...' if len(self.body) > 100 else self.body

djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'userForm': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'loginForm': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

djangonautic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', { 'articles': articles })

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'articlesWithSlug':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to DB
            articleInstance = form.save(commit=False)
            articleInstance.author = request.user
            articleInstance.save()
            return redirect('articles:list')

    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'articleForm': form })

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('this is a Homepage')
    return render(request, 'homepage.html')

def about(request):
    #return HttpResponse('its the about page')
    return render(request, 'about.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

  <h1>Login</h1>
  <!-- <form class="site-form" action="/accounts/login/" method="post"> -->
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ loginForm }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>

{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

  <h1>Signup</h1>
  <!-- <form class="site-form" action="/accounts/signup/" method="post"> -->
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ userForm }}

    <input type="submit" value="Signup">
  </form>

{% endblock %}

djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create">
  <h2>Create awesome new article</h2>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ articleForm }}
    <input type="submit" value="Create">
  </form>
</div>

{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
  <div class="article">
    <img src="{{ articlesWithSlug.thumb.url }}" alt="{{ articlesWithSlug.thumb }}">
    <!-- <p>{{ articlesWithSlug.thumb.url }}</p> -->
    <h2>{{ articlesWithSlug.title }}</h2>
    <p>{{ articlesWithSlug.body }}</p>
    <p>{{ articlesWithSlug.date }}</p>
  </div>
</div>

{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}

<h1><u>Article List</u></h1>
<div class="articles">
  {% for article in articles %}
    <div class="article" style="margin: 0 auto; width: 50%">
      <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
      <p>{{ article.snippet }}</p>
      <p>{{ article.date }}</p>
    </div>
    <hr>
  {% endfor %}
</div>

{% endblock %}

<!--
{% block mainC %}
<h2><i>this is test content for mainC block</i></h2>
{% endblock %}
-->

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About - djangonautic</title>
  </head>
  <body>
    <h1>About djangonautic app</h1>
    <p>You can find nothing right now</p>
    <p>This is site is under construction right now</p>
    <p>Please keep looking for further updates</p>
  </body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Djangonauts</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <header class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" style="height: 100px; width: 100px;" alt="Article Logo" /></a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
              </form>
            </li>
            <li>
              <a href="{% url 'articles:create' %}" class="highlight">Create New Article</a>
            </li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
    <!--
    <div class="mainContent">
      {% block mainC %}
      {% endblock %}
    </div>
    -->
  </body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the Homepage for my first app</h1>
    <p>Welcome to djangonautic app</p>
  </body>
</html>